# Generated by Django 5.0.6 on 2024-06-13 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barquillo',
            fields=[
                ('idBarquillo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Barquillo')),
                ('nombreBarquillo', models.CharField(max_length=20, verbose_name='Nombre Barquillo')),
            ],
        ),
        migrations.CreateModel(
            name='Helados',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id')),
                ('rango', models.CharField(max_length=20, verbose_name='Rango')),
                ('cantidad', models.CharField(max_length=20, verbose_name='Cantidad')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('barquillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barquillo', verbose_name='Barquillo')),
            ],
        ),
    ]
