# Generated by Django 5.0.6 on 2024-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helados',
            name='sabor',
            field=models.CharField(default=0, max_length=20, verbose_name='Sabor'),
        ),
    ]
