# Generated by Django 5.0.6 on 2024-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_helados_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helados',
            name='sabor',
            field=models.CharField(default=0, max_length=35, verbose_name='Sabor'),
        ),
    ]
