# Generated by Django 5.0.6 on 2024-06-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_boleta_helados_precio_detalle_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helados',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
