# Generated by Django 5.0.6 on 2024-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_helados_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helados',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='helados',
            name='sabor',
            field=models.CharField(max_length=35, verbose_name='Sabor'),
        ),
    ]
